### ISSUE TITLE
Android applicationIdSuffix breaks module

### ISSUE THREAD

**Issue by ncnlinh** [luggg/react-native-config#14]
With the current Gradle build, you can declare an applicationIdSuffix for different flavors or put your applicationId as different from `AndroidManifest.xml`'s packagename. This will makes RN-config throws "Could not find BuildConfig class" since `Class.forName(getReactApplicationContext().getApplicationContext().getPackageName() + ".BuildConfig")` returns the incorrect class package. 

This might be helpful as a fix http://stackoverflow.com/questions/21365928/gradle-how-to-use-buildconfig-in-an-android-library-with-a-flag-that-gets-set/31587838#31587838

**Comment by pedro** [comment]
Fixed in #15.
