### ISSUE TITLE
Config is undefined

### ISSUE THREAD

**Issue by timscott** [luggg/react-native-config#16]
I'm getting an error:

> ExceptionsManager.js:61 Cannot read property 'API_BASE_URL' of undefined

I tried this:
```import Config from 'react-native-config';```
and this:
```let Config = require('react-native-config');```

Debugging I can see that Config is ```undefined```.

I tried with an without specifying ```ENVFILE```. 

Ideas?

**Comment by pedro** [comment]
Odd, what version are you on? Did you do the ios and/or android setup?

**Comment by jarecsni** [comment]
Hi, 

I'm facing the same issue, did you manage to get to the bottom of this?

Thanks,
Janos

**Comment by jarecsni** [comment]
Actually it is caused by not running the rnpm command so an RTFM issue - apologies :)

**Comment by pedro** [comment]
No problem, thanks for sharing the solution!

**Comment by Arelav** [comment]
rnpm-install info Android module react-native-config is already linked
rnpm-install info iOS module react-native-config is already linked
And Config.KEY_NAME is undefined

Only:
{
  APPLICATION_ID: 'com.ignitern',
    VERSION_CODE: 1,
    VERSION_NAME: '1.0',
    FLAVOR: '',
    DEBUG: true,
    BUILD_TYPE: 'debug'
}
Not keys I set in .env
May be it Ignite issue not react-native-config, but I will happy to accept any information.

**Comment by efratyo** [comment]
@Arelav  Did you manage to get it work?
I'm facing this issue as well.
on Android everything works great, but on IOS I get 'undefined' on Config keys.
Also package is already linked.

**Comment by jpmazza** [comment]
Hey  @efratyo,  I'm facing a similar issue. On Android, it is working great, but on ios the `Config` object is empty.
Did you find any solution?

**Comment by scalfs** [comment]
I'm having the same issue! Did you guys find any solutions?

**Comment by tarun29061990** [comment]
Did you guys find any solution regarding this ??
I am getting this as output
{
  "FLAVOR": "",
  "DEBUG": true,
  "VERSION_CODE": 1,
  "BUILD_TYPE": "debug",
  "APPLICATION_ID": "com.canvas",
  "VERSION_NAME": "1.0"
}

Config.API_URL is undefined

**Comment by pmemids** [comment]
@tarun29061990 Did you get any solution on this?
