### ISSUE TITLE
Can we refer to variables set in .env from MainActivity.java?

### ISSUE THREAD

**Issue by danielweinmann** [luggg/react-native-config#2]
Hi there,

I'm setting CodePush up on Android and for that I have to reference a deployment key on MainActivity.java. The best way for me to do that would be to add this deployment key to my `.env` and refer it on MainActivity.java.

Is that possible? If so, how can I accomplish that?

Thanks for the package!

**Comment by pedro** [comment]
Hey!

Absolutely, the configs are available to any Java class via `BuildConfig`; I believe this class is just available to all your classes. Just updated the readme to reflect this.

Thanks!

**Comment by danielweinmann** [comment]
Thanks, man! It works :D
