### ISSUE TITLE
iOS support for different environments

### ISSUE THREAD

**Issue by danielweinmann** [luggg/react-native-config#5]
@pedro, do you have an idea about when will this be available?

If you instruct me I can send a PR. But I don't have much experience with XCode, so I'll probably need help.

From what I can imagine, we would probably have to find a way to access `ENVFILE` var [here](https://github.com/luggg/react-native-config/blob/master/ios/ReactNativeConfig.xcodeproj/project.pbxproj#L146) and pass it to our ruby script. But I have no idea if that's possible or how to accomplish that ;)

**Comment by pedro** [comment]
Hey! Still a bit experimental, but I just added support for picking different environments to iOS in 0.0.4.

You can read about it on the readme:
https://github.com/luggg/react-native-config#different-environments

Really wish we could use environment vars on the scheme but those are not available to run scripts :{
Even worse, I don't know of a folder that both scripts can share to save that `envfile`, so ended up going with just `/tmp/` for now. Any ideas for improvement are welcome!

Thanks,
